### ISSUE TITLE
Effort import needs to be async

### ISSUE THREAD

**Issue by moveson** [SplitTime/OpenSplitTime#505]
Importing more than ~150 efforts results in a timeout. Effort import needs to be async with import jobs and a way to check on them, similar to how we did this in Wall-e.

Path to completion:

- [x] Upgrade Stimulus to 2.0 (#513)
- [x] Upgrade Turbolinks to Turbo (#514)
- [x] Create `import_jobs` table (#515)
- [x] Create model and views (#516)
- [x] Convert views to Turbo Streams
- [x] Point existing import endpoints at the new model
